### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by joefrancois** [nTier-Software/Shopify-iDempiere#1]
Hello,

Thank you very much for the module. I review the installation instruction, and I couldn't pass the first step as it asks to Packin a zip file that does not seem to exist in this version.  Could you please assist me in implementing the module?

Regards,
Joseph

**Comment by nTier-Software** [comment]
Thanks Joseph,

Uploaded now

**Comment by joefrancois** [comment]
Thank you for the quick response. I Packin the zip file and loaded the plugin  Shopify-ntierza.co.ntier.shopify. The system could not load the plugin. I am running Idempiere Logilite 7.2

I get the following errors:

Felix Console: 

Symbolic Name | za.co.ntier.shopify
-- | --
Version | 1.0.0.202102191113
Bundle Location | inputstream:za.co.ntier.shopify_1.0.0.202102191113.jar
Last Modification | Sun Feb 28 12:51:05 UTC 2021
Vendor | nTier Software Services
Start Level | 5
Bundle Classpath | .,com.fasterxml.jackson.core.jackson-core_2.10.0.jar,com.fasterxml.jackson.core.jackson-databind_2.10.0.jar,org.apache.commons.codec_1.13.0.v20200108-0001.jar,org.apache.httpcomponents.httpclient_4.5.10.v20200114-1512.jar,org.apache.httpcomponents.httpcore_4.4.12.v20200108-1212.jar,commons-logging.jar,com.fasterxml.jackson.core.jackson-annotations_2.10.0.jar
Exported Packages | za.co.ntier.factoriesza.co.ntier.modelza.co.ntier.processesza.co.ntier.shopify
Imported Packages | **org.osgi.framework,version=1.10.0 -- Cannot be resolved**
Manifest Headers | Bundle-Name: Shopify-ntierBundle-ClassPath: ., com.fasterxml.jackson.core.jackson-core_2.10.0.jar, com.fasterxml.jackson.core.jackson-databind_2.10.0.jar, org.apache.commons.codec_1.13.0.v20200108-0001.jar, org.apache.httpcomponents.httpclient_4.5.10.v20200114-1512.jar, org.apache.httpcomponents.httpcore_4.4.12.v20200108-1212.jar, commons-logging.jar, com.fasterxml.jackson.core.jackson-annotations_2.10.0.jarManifest-Version: 1.0Service-Component: ProcessFactory.xmlBundle-RequiredExecutionEnvironment: JavaSE-11Automatic-Module-Name: Shopify-ntierBundle-ActivationPolicy: lazyBundle-SymbolicName: za.co.ntier.shopify; singleton:=trueBundle-Vendor: nTier Software ServicesRequire-Bundle: org.adempiere.base; bundle-version="8.1.0", org.adempiere.plugin.utils; bundle-version="8.1.0", org.eclipse.equinox.ds; bundle-version="1.6.200", org.eclipse.equinox.event; bundle-version="1.5.500"Bundle-Activator: org.adempiere.plugin.utils.AdempiereActivatorImport-Package: org.osgi.framework; version="1.10.0"Bundle-ManifestVersion: 2Export-Package: za.co.ntier.factories, za.co.ntier.model, za.co.ntier.processes, za.co.ntier.shopifyBundle-Version: 1.0.0.202102191113


Log file:

*** 2021-02-28 12:51:05.106 idempiere Log (CLogFile) ***
12:51:05.105-----------> osgi.warn: Cannot install or update bundle from /tmp/install15180454879492387040.tmp [488]
org.osgi.framework.BundleException: Could not resolve module: za.co.ntier.shopify [346]
  Unresolved requirement: Import-Package: org.osgi.framework; version="1.10.0"

	at org.eclipse.osgi.container.Module.start(Module.java:451)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:450)
	at org.apache.felix.webconsole.internal.core.InstallHelper.doRun(InstallHelper.java:67)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.doRun(BaseUpdateInstallHelper.java:99)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.run(BaseUpdateInstallHelper.java:171)
	at java.base/java.lang.Thread.run(Thread.java:834)

Regards
Joseph
--

**Comment by nTier-Software** [comment]
Hi, I am thinking it's probably the iDempiere version.

You want to try it on: https://test.idempiere.org/ just to rule out the version  of ID?

**Comment by joefrancois** [comment]
Hello,

I am part of the ERP Academy, and I  have spoken about the issue with @chuboe. @chuboe proposed to engage Logilite to make the module backwards compatible with Logilite iDempiere 7.1 if you so wish.  What do you think?

Regards,
Joseph

**Comment by nTier-Software** [comment]
I have generated a new plugin. Please try with that and let me know.
